s_expression : atomic
             | list

list : "(" s_expression <s_expression> ")"

atomic : letter atom_part

atom_part : empty
          | letter atom_part
          | number atom_part

letter : [!|$|%|&|*|+|-|.|/|:|<|=|>|?|@|^|_|~|a-z|A-Z]

number = [0-9]

empty = " "
