# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

steps:
- bash: sudo apt-get install libpcap-dev
  condition: eq( variables['Agent.OS'], 'Linux' )

- bash: sudo apt-get install clang
  condition: eq( variables['Agent.OS'], 'Linux')

- bash: sudo apt-get install clang-format
  condition: eq( variables['Agent.OS'], 'Linux')

- task: CmdLine@2
  inputs:
    script: |
      git clone https://libwebsockets.org/repo/libwebsockets
      cd libwebsockets
      mkdir build
      cd build
      cmake ..
      sudo make install

- task: NodeTool@0
  inputs:
    versionSpec: '>=13.9.0'
    checkLatest: true

- task: Bash@3
  inputs:
    filePath: 'build.sh'
    noProfile: true
