# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
pool:
  vmImage: $(imageName)


steps:
- bash: sudo apt-get install libpcap-dev
  condition: eq( variables['Agent.OS'], 'Linux')
  displayName: 'Install libpcap'

- script: 'install_libwebsockets.sh'
  displayName: 'Install libwebsockets'

- bash: |
    export OPENSSL_ROOT_DIR=/usr/local/ssl
    export OPENSSL_LIBRARIES=/usr/local/ssl/lib
  condition: eq( variables['Agent.OS'], 'Darwin')
  displayName: 'Setting OpenSSL paths'

- task: NodeTool@0
  inputs:
    versionSpec: '>=13.9.0'
    checkLatest: true

- task: CMake@1
  inputs:
    cmakeArgs: '..'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'make'
    workingDirectory: 'build'
  displayName: 'make'
