# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

steps:
- bash: sudo apt-get install g++-9
  condition: eq( variables['Agent.OS'], 'Linux')
  displayName: 'Installing GCC'

- bash: sudo apt-get install libpcap-dev
  condition: eq( variables['Agent.OS'], 'Linux')
  displayName: 'Install libpcap'

- bash: sudo apt-get install clang
  condition: eq( variables['Agent.OS'], 'Linux')
  displayName: 'Install clang'

- bash: sudo apt-get install clang-format
  condition: eq( variables['Agent.OS'], 'Linux')
  displayName: 'Install clang-format'

- task: NodeTool@0
  inputs:
    versionSpec: '>=13.9.0'
    checkLatest: true

- task: Bash@3
  inputs:
    filePath: 'build.sh'
    noProfile: false
    noRc: false
    displayName: 'Building with GCC and Clang'
